### ISSUE TITLE
When Form is Valid

### ISSUE THREAD

**Issue by donniefitz2** [pridees/combine-validate#4]
I haven't been able to figure out how to know when all form fields are valid. For instance, I have several fields and I want to disable the save button until the fields are all valid. I have a boolean property disabling the save button called isFormDisabled that I want to enable once all of the fields are valid. 

Here's what I have in my view model: 
`@Published var firstName = ""
    @Published var lastName = ""
    @Published var userName = ""
    @Published var vehicleYear = ""
    @Published var vehicleMake = ""
    @Published var vehicleModel = ""
    @Published var vehicleNickName = ""
   
    public lazy var emtpyFirstNameValidator: ValidationPublisher = {
        $firstName.validateNonEmpty(error: "Please enter your first name", tableName: nil)
    }()
    
    public lazy var emptyLastNameValidator: ValidationPublisher = {
        $lastName.validateNonEmpty(error: "Please enter your last name", tableName: nil)
    }()
    
    public lazy var emptyUserNameValidator: ValidationPublisher = {
        $userName.validateNonEmpty(error: "Please create a username", tableName: nil)
    }()
    
    public lazy var vehicleYearValidator: ValidationPublisher = {
        $vehicleYear.validateWithRegex(regex: CustomRegexPatterns.vehicleYear, error: "Please enter a valid vehicle year", tableName: nil)
    }()
    
    public lazy var emptyVehicleMakeValidator: ValidationPublisher = {
        $vehicleMake.validateNonEmpty(error: "Please enter your vehicle make", tableName: nil)
    }()
    
    public lazy var emptyVehicleModelValidator: ValidationPublisher = {
        $vehicleModel.validateNonEmpty(error: "Please enter your vehicle model", tableName: nil)
    }()`

I reviewed the examples, but I'm not quite sure how to know when the form is valid. 

Thanks.

**Comment by pridees** [comment]
There is very expressive native way to figure out all validation results

You can use the CombineLatest from Combine to make this job.
Because CombineLatest can work with 4 max publishers, thus you can make composition from several CombineLatest publishers.

```swift

// Firstly, define the validationResult property
@Published public var validationResult = false

// cancellables store 
private var cancellables = Set<AnyCancellable>()

// then 
init() {
    let userGroupValidators = Publishers.CombineLatest3(
            emtpyFirstNameValidator,
            emptyLastNameValidator,
            emptyUserNameValidator
       )
      .map { $0.isSuccess && $1.isSuccess && $2.isSuccess  }
    
    let vehicleGroupValidators = Publishers.CombineLatest3(
           vehicleYearValidator,
           emptyVehicleMakeValidator,
           emptyVehicleModelValidator
       )
      .map { $0.isSuccess && $1.isSuccess && $2.isSuccess  }
      
    Publishers.CombineLatest(userGroupValidators, vehicleGroupValidators)
       .map { $0 && $1 }
       .assign(to: \.validationResult: on: self)
       .store(on: &cancellables)

}
```

`validationResult` will be false until the all fields is not success

Feel free if you will have any questions yet.
